### PR TITLE
updated with parser options for usability

### PR DESCRIPTION
**Pull request by jhcollins**
*NOAA CLI options added for url request
*DSS CLI options added for tsc class arguments

### CODE REVIEW

**Comment by jhcollins** [comment]
@Tich1212 It appears that I don't have permissions to request specific reviewers. Figured you'd be the one to review and approve.

**Review by Tich1212 — CHANGES_REQUESTED** [review]
Can you add on to the description to include something about how it is intended to be executed and how you are passing in those options?

**Review by Tich1212 — APPROVED** [review]
Great!

**Comment by jhcollins** [comment]
thanks

**Pull request merged**
